PortalPacjentaSopel/Controllers/PortalPacjentaController.cs
using PortalPacjenta.DAL;
using PortalPacjenta.Infrastructure;
using PortalPacjenta.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortalPacjenta.Controllers
{
    public class PortalPacjentaController : PortalPacjentaMasterController
    {
        SopelContext db = new SopelContext();
         
        // GET: PortalPacjenta
        public ActionResult Index()
        {
            return View();
        }

        //public ActionResult Logowanie()
        //{
        //    Uzytkownik user = new Uzytkownik();
        //    return View(user);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken] //generuje losowy żeton przy formularzu (zabezpieczenie przed atakiem CSRF)
        //public ActionResult Logowanie(Uzytkownik userModel)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        if (db.Uzytkownicy.Any(u => u.Login == userModel.Login) && (db.Uzytkownicy.Single(u => u.Login == userModel.Login) as Uzytkownik).Haslo == userModel.Haslo)
        //        {
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    return View(userModel);
        //}
    }
}

PortalPacjentaSopel/Controllers/RejestracjaOnlineController.cs
using PortalPacjenta.DAL;
using PortalPacjenta.Infrastructure;
using PortalPacjenta.Models;
using PortalPacjenta.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PortalPacjenta.Controllers
{
    [Authorize]
    public class RejestracjaOnlineController : PortalPacjentaMasterController
    {
        SopelContext db = new SopelContext();


        // GET: Rejestracja
        public ActionResult Index()
        {
            var model = pobierzTerminarzViewModel(DateTime.Today.ToString("yyyy-MM-dd"));

            return View("~/Views/PortalPacjenta/RejestracjaOnline/Index.cshtml", model);
        }

        private TerminarzViewModel pobierzTerminarzViewModel(string wybranaData = null, int pracownikId = 0)
        {
            List<Opcja> opcje = null;
            List<Pracownik> prac = null;
            List<Rezerwacja> rez = null;

            if (wybranaData != null)
            {
                wybranaData = String.Format("{0:yyyy-MM-dd}", wybranaData);

                DateTime data = new DateTime(
                    Convert.ToInt32(wybranaData.Substring(0, 4)),
                    Convert.ToInt32(wybranaData.Substring(5, 2)),
                    Convert.ToInt32(wybranaData.Substring(8, 2))
                    );

                rez = db.Rezerwacje.Where(r => r.DataRezerwacji == data).ToList();
            }
            else
            {
                rez = db.Rezerwacje.ToList();
            }

            if (pracownikId > 0)
            {
                prac = db.Pracownicy.Where(p => p.ID == pracownikId).ToList();
            }
            else
            {
                prac = db.Pracownicy.ToList();
            }

            opcje = db.Opcje.ToList();
            var model = new TerminarzViewModel { opcje = opcje, pracownicy = prac, rezerwacje = rez };

            return model;
        }

        public ViewResult pobierzTerminarzWybranegoLekarza(string data, int idi = 0)
        {
            var model = pobierzTerminarzViewModel(data, idi);

            ViewBag.GodzOd = model.opcje.Single(o => o.Nazwa == "term_godz_od").Wartosc;
            ViewBag.GodzDo = model.opcje.Single(o => o.Nazwa == "term_godz_do").Wartosc;
            ViewBag.CzasWiz = model.opcje.Single(o => o.Nazwa == "term_czas_wiz").Wartosc;

            return View("~/Views/PortalPacjenta/RejestracjaOnline/SiatkaTerminarza.cshtml", model);
        }

        public JsonResult pobiarzWybranaSpecjalizacje(string spec = "")
        {
            if (string.IsNullOrEmpty(spec))
            {
                return Json(db.Pracownicy.ToList());
            }
            else
            {
                return Json(db.Pracownicy.Where(p => p.Specjalizacja == spec).ToList());
            }
        }

            

        public JsonResult ListaPracownikow(string spec)
        {
            List<Pracownik> pracownicy = new List<Pracownik>();

            //Database.otworzPolaczenie("serwer1518407.home.pl", "18292517_0000002", "Sopel2016", "18292517_0000002");
            //NpgsqlDataReader dr = Database.wykonajZapytanieDQL("SELECT * FROM pracownicy where specjalizacja like '" + spec + "'");

            //while (dr.Read())
            //{
            //    pracownicy.Add(new Pracownik() { Id = (int)dr["id"], Imie = dr["imie"].ToString(), Nazwisko = dr["nazwisko"].ToString(), Specjalizacja = dr["specjalizacja"].ToString() });
            //}

            //dr.Close();

            return Json(pracownicy);
        }

        [HttpPost]
        public ActionResult Index(Rezerwacja rezerwacja, string idrez)//idrez ma następujący format idLekarza-godzina-data
        {
            //Database.otworzPolaczenie("serwer1518407.home.pl", "18292517_0000002", "Sopel2016", "18292517_0000002");

            //string[] rez = idrez.Split('-');

            //NpgsqlDataReader dr = Database.wykonajZapytanieDQL("SELECT count(pesel) from pacjenci where pesel = '" + rezerwacja.Pacjent.Pesel + "'");
            //dr.Read();
            //if (dr[0].ToString() == "0")
            //{
            //    dr.Close();

            //    Database.wykonajZapytanieDML("INSERT INTO pacjenci (imie,nazwisko,pesel,dok_toz,telefon,email,plec)" +
            //        "VALUES('" + rezerwacja.Pacjent.Imie.ToUpper() + "', '" + rezerwacja.Pacjent.Nazwisko.ToUpper() + "', '"
            //        + rezerwacja.Pacjent.Pesel + "', '" + rezerwacja.Pacjent.DokumentTozsamosci.ToUpper()
            //        + "', '" + rezerwacja.Pacjent.Telefon.ToUpper() + "', '"
            //        + rezerwacja.Pacjent.Email.ToUpper() + "', '" + rezerwacja.Pacjent.Plec.ToUpper() + "')");
            //}
            //dr.Close();
            //dr = Database.wykonajZapytanieDQL("Select id from pacjenci where pesel = '" + rezerwacja.Pacjent.Pesel + "'");

            //dr.Read();

            //string id = dr["Id"].ToString();

            //dr.Close();

            //Database.wykonajZapytanieDML("INSERT INTO REZERWACJE (ID_PRACOWNIKA,ID_PACJENTA,data)" +
            //    "VALUES(" + rez[0] + ", " + id + ", '" + rezerwacja.DataRezerwacji.ToString("yyyy-MM-dd") + " " + rezerwacja.GodzinaRezerwacji + "')");

            //Database.zamknijPolaczenie();
            return RedirectToAction("Index");
        }



        public ActionResult wczytaj()
        {
            Pacjent pac = new Pacjent();
            //NpgsqlDataReader wynik = Database.wykonajZapytanieDQL("Select * from pacjenci");
            //while (wynik.Read())
            //{
            //    pac.Imie = wynik[2] as string;
            //    pac.Nazwisko = wynik[1] as string;
            //}
            //Database.zamknijPolaczenie();

            return View("Index", pac);
        }

        public JsonResult GetJsonPrac(string term)
        {
            List<string> listaPracowników = new List<string>();
            //NpgsqlDataReader dr = Database.wykonajZapytanieDQL("Select imie || ' ' || nazwisko || ' (' || specjalizacja || ')' from pracownicy");
            //while (dr.Read())
            //{
            //    if((dr[0]as string).ToUpper().Contains(term.ToUpper()))
            //    listaPracowników.Add(dr[0].ToString());
            //}

            //Database.zamknijPolaczenie();

            return Json(listaPracowników, JsonRequestBehavior.AllowGet);
        }


        //public ActionResult pokazLekarza(Rezerwacja rezerwacja)
        //{
        //    List<Pracownik> wybranyLekarz = new List<Pracownik>();

        //    Database.otworzPolaczenie("serwer1518407.home.pl", "18292517_0000002", "Sopel2016", "18292517_0000002");

        //    NpgsqlDataReader dr = Database.wykonajZapytanieDQL("Select * from prac"); /*from prac where nazw=" + rezerwacja.pracownik.nazwisko);*/

        //    while (dr.Read())
        //    {
        //        wybranyLekarz.Add(new Pracownik() { id = (int)dr["id"], imie = dr["imie"].ToString(), nazwisko = dr["nazw"].ToString(), specjalizacja = dr["spec"].ToString() });
        //    }

        //    ViewBag.pokazLekarza = wybranyLekarz;

        //    return View();
        //}
    }
}

PortalPacjentaSopel/Views/PortalPacjenta/RejestracjaOnline/SiatkaTerminarza.cshtml
@model PortalPacjenta.ViewModels.TerminarzViewModel

<table class="table table-bordered terminarz">
    <tr>
        <td></td>
        @{
            int iloscPracowników = Model.pracownicy.Count;
            string szer = "100%";
            if (iloscPracowników > 0)
            {
                szer = (90 / iloscPracowników).ToString() + "%";
            }

            foreach (var prac in Model.pracownicy)
            {
                <td class="panelNazwyPracownika" style="width:@szer">@prac.Imie @prac.Nazwisko</td>
            }
        }
    </tr>
    @{
        TimeSpan time = new TimeSpan(Convert.ToInt32(ViewBag.GodzOd.Substring(0, 2)), Convert.ToInt32(ViewBag.GodzOd.Substring(3, 2)), 0);
        TimeSpan maxTime = new TimeSpan(Convert.ToInt32(ViewBag.GodzDo.Substring(0, 2)), Convert.ToInt32(ViewBag.GodzDo.Substring(3, 2)), 0);
        while (time <= maxTime)
        {
            string timeString = string.Format("{0:00}", time.Hours) + ":" + string.Format("{0:00}", time.Minutes);
            <tr>
                <td class="terminarzPanelGodzin">@timeString</td>

                @{
                    for (int y = 0; y < iloscPracowników; y++)//Tworzy kolumnę dla każdego pracownika
                    {
                        bool rezerwacjaIstnieje = false;
                        int idRez = 0;

                        foreach (var item in Model.rezerwacje)
                        {
                            string dataRez = item.DataRezerwacji.Year + "-" + string.Format("{0:00}", item.DataRezerwacji.Month) + "-" + string.Format("{0:00}", item.DataRezerwacji.Day);
                            if (Model.pracownicy[y].ID == item.Pracownik.ID && item.godzOd == time.ToString().Substring(0, 5))
                            {
                                rezerwacjaIstnieje = true;
                                break;
                            }
                        }
                        if (rezerwacjaIstnieje)
                        {
                            <td id="@Model.pracownicy[y].ID-@timeString" class="terminarzZarezerwowanyTermin">
                                   Brak terminu
                            </td>
                            rezerwacjaIstnieje = false;
                        }
                        else
                        {
                            <td id="@Model.pracownicy[y].ID-@timeString" class="panel-rezerwacji wolny-termin" data-action-url="@Url.Action("pokazOknoRezerwacji", "RejestracjaOnline")">Umów wizytę</td>
                        }
                    }
                }
            </tr>
                        time = time.Add(new TimeSpan(0, Convert.ToInt32(@ViewBag.CzasWiz), 0));
                        // time = time.Add(new TimeSpan(0, 5, 0));
                    }
    }
</table>

PortalPacjentaSopel/Views/PortalPacjenta/RejestracjaOnline/index.cshtml
@model PortalPacjenta.ViewModels.TerminarzViewModel

@{
    ViewBag.Title ="Umów wizitę";
    Layout ="~/Views/_Layout.cshtml";
}

@section style{
    @Styles.Render("~/Content/RejestracjaOnline")
}


<div class="portalPacjenta">
    <div class="container kontenerMaterial">
        <div class="container">
            <div id="terminarzDataKontener" class="col-sm-4">
                <label for="dataRezerwacji">Data</label>
                <input type="text" value="@DateTime.Now.Year-@string.Format("{0:00}", DateTime.Now.Month)-@string.Format("{0:00}",DateTime.Now.Day)" id="dataRezerwacji" name="dataRezerwacji" class="form-control datepickerRejOnline" />
            </div>
            <div class="col-sm-4">
                <label for="lekarz">Lekarz</label>
                <select class="form-control" id="wyborLekarzaRejOnline">
                    <option>Wybierz lekarza</option>
                    @{
                        foreach (var prac in Model.pracownicy)
                        {
                            <option id="@prac.ID">@prac.Imie @prac.Nazwisko (@prac.Specjalizacja)</option>
                        }
                    }
                </select>
            </div>
            <div class="col-sm-4">
                <label for="specjalizacja">Specjalizacja</label>
                <select class="form-control" id="wyborSpecjalizacjiPortalPacjenta" onchange="wybranoSpecjalizacje(this)">
                    <option></option>
                    @{
                        foreach (var spec in Model.pracownicy.Select(p => p.Specjalizacja).Distinct())
                        {
                            <option id="@spec">@spec</option>
                        }
                    }
                </select>
            </div>
        </div>
    </div>

    <div class="container kontenerMaterial" id="podpowiedzi">
        <div class="col-sm-4  podpowiedz">
            <img class="img-responsive" src="~/Content/Images/plannerIcon.png" alt="Ikonka kalendarza" style="float:left" />
            <img class="hidden-xs img-responsive" src="~/Content/Images/Up 2.png" alt="Ikonka kalendarza" style="float:right" />
            <p style="float:left">Wybierz, aby określić datę rezerwacji</p>
        </div>
        <div class="col-sm-4  podpowiedz">
            <img class="img-responsive" src="/Content/Images/doctorIcon.png" alt="Ikonka lekarza" style="float:left" />
            <img class="hidden-xs img-responsive" src="~/Content/Images/Up 2.png" alt="Ikonka kalendarza" style="float:right" />
            <p style="float:left">Wybierz, aby wyświetlić listę lekarzy</p>
        </div>
        <div class="col-sm-4  podpowiedz">
            <img class="img-responsive" src="/Content/Images/clinicIcon.png" alt="Ikonka kliniki" style="float:left" />
            <img class="hidden-xs img-responsive" src="~/Content/Images/Up 2.png" alt="Ikonka kalendarza" style="float:right" />
            <p style="float:left">Wybierz, aby wyświetlić lekarzy danej specjalności</p>
        </div>
    </div>

    <div class="container kontenerMaterial " id="kontenerMaterialPortalPacjenta" style="padding:0">
        @*Treść ładowana AJAXem*@
    </div>

    @*@Html.Partial("_KartaRezerwacjiPortalPacjentaNiezalogowany")*@
</div>
    <script>

        /// <reference path="jquery-3.1.1.js" />
        

        //Pobranie z bazy listy pracowników po wybranej specjalizacji
        function wybranoSpecjalizacje(specList) {
            
        }
    </script>
@section scripts{
    @Scripts.Render("~/Scripts/RejestracjaOnline")
}