SOPeL/Controllers/AdminController.cs
using SOPeL.DAL;
using SOPeL.Infrastructure;
using SOPeL.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace SOPeL.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        SopelContext db = new SopelContext();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PokazOpcjeGlowne()
        {
            OpcjeGlowneViewModel model = new OpcjeGlowneViewModel() { ogol_podz_imie_nazw =  db.Opcje.Single(o => o.Nazwa == "ogol_podz_imie_nazw").Wartosc};
            return PartialView("_OknoOpcjiGlownych", model);

        }

        [HttpPost]
        public ActionResult ZapiszOpcjeGlowne(OpcjeGlowneViewModel model)
        {
            var opcja = db.Opcje.Single(o => o.Nazwa == "ogol_podz_imie_nazw");
            opcja.Wartosc = model.ogol_podz_imie_nazw;
            db.Entry(opcja).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

SOPeL/Controllers/WizytaController.cs
using SOPeL.DAL;
using SOPeL.Infrastructure;
using SOPeL.Models;
using SOPeL.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace SOPeL.Controllers
{
    [Authorize]
    public class WizytaController : Controller
    {
        SopelContext db = new SopelContext();
        //GET: Poczekalnia
        public ActionResult Index()
        {
            var data = DateTime.Today.ToString("yyyy-MM-dd");
            var model = PrzygotujWizytaViewModel(data);

            return View(model);

        }
        public ActionResult WyswietlanieLekarzy(int? idlekarza)
        {
            if ((idlekarza == null) || (idlekarza == 0))
            {
                var prac = db.Pracownicy.ToList();
                var wiz = db.Wizyty.ToList();
                var rez = db.Rezerwacje.Where(r => r.Stat == Status.Rezerwacja && r.Aktw == Aktywny.Tak).ToList();
                var model = new WizytaViewModel { pracownicy = prac, rezerwacje = rez, wizyty = wiz };
                return PartialView("WizytaPrzychodnia", model);
            }
            else
            {
                var prac = db.Pracownicy.ToList();
                var wiz = db.Wizyty.ToList();
                var rez = db.Rezerwacje.Where(r => r.PracownikID == idlekarza && r.Stat == Status.Rezerwacja && r.Aktw == Aktywny.Tak).ToList();
                var model = new WizytaViewModel { pracownicy = prac, rezerwacje = rez, wizyty = wiz };
                return PartialView("WizytaPrzychodnia", model);
            }
        }

        public PartialViewResult PobierzListeRezerwacji(string data, Status status = Status.Rezerwacja, int idlekarza = 0)
        {
            data = data ?? DateTime.Today.ToString("rrrr-MM-dd");
            var model = PrzygotujWizytaViewModel(data, status, idlekarza);
            return PartialView("WizytaPrzychodnia", model);
        }

        private PoczekalniaViewModel PrzygotujWizytaViewModel(string data, Status status = Status.Rezerwacja, int idlekarza = 0)
        {
            var prac = db.Pracownicy.ToList();
            var wiz = db.Wizyty.ToList();
            List<Rezerwacja> rez;
            DateTime dataRez = DateTime.Parse(data);

            if (idlekarza == 0)
            {
                rez = db.Rezerwacje.Where(r => r.DataRezerwacji == dataRez && r.Aktw == Aktywny.Tak && r.Stat == status).OrderBy(r => r.DataRezerwacji).ThenBy(r => r.godzOd).ToList();
            }
            else
            {
                rez = db.Rezerwacje.Where(r => r.DataRezerwacji == dataRez && r.PracownikID == idlekarza && r.Aktw == Aktywny.Tak && r.Stat == status).OrderBy(r => r.DataRezerwacji).ThenBy(r => r.godzOd).ToList();
            }

            return new PoczekalniaViewModel
            {
                pracownicy = prac,
                rezerwacje = rez,
                FiltryPoczekalni = new FiltryPoczekalni
                {
                    WybranaData = data,
                    WybranyLekarz = idlekarza,
                    StatusRezerwacji = status
                }
            };
        }


        public ActionResult UsunRezerwacje(int idRez, string wybranaData, int idLekarza, Status stat)
        {
            try
            {
                RezultatAkcji result = RezerwacjeManager.UsunRezerwacje(idRez);

                if (result.RezultatPozytywny)
                {
                    return RedirectToAction("PobierzListeRezerwacji", new { data = wybranaData, idlekarza = idLekarza, status = stat });
                }
                else
                {
                    throw new Exception("Alarm!");
                }
            }
            catch (Exception ex)
            {

                throw ex;
            }

        }

        public PartialViewResult dodajWizyte(int idrez)
        {

            Wizyta wizyta = new Wizyta();
            Rezerwacja rezerwacja = db.Rezerwacje.Find(idrez);
            wizyta.Pacjent = rezerwacja.Pacjent;
            wizyta.RezerwacjaId = rezerwacja.Id;
            wizyta.DataWizyty = DateTime.Now;
            wizyta.DataModyfikacji = DateTime.Now;
            wizyta.PacjentID = rezerwacja.PacjentID;
            wizyta.PracownikID = rezerwacja.PracownikID;

            return PartialView("_KartaWizyty", wizyta);
        }

        public JsonResult ICD10Autocomplete(string term)
        {
            var icd10 = db.KodyICD10.Select(i => i.Kod + " - " + i.Nazwa).Where(i => i.StartsWith(term)).ToList();

            return Json(icd10, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LekiAutocomplete(string term)
        {
            var leki = db.Leki.Select(i => i.Nazwa + " | op. " + i.Opakowanie + " | d. " + i.Dawka).Where(i => i.StartsWith(term)).ToList();

            return Json(leki, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DodajLek(string nazwa, string dawk, string odpl)
        {
            var lek = nazwa + ", dawk: " + dawk ;

            return Json(lek, JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult WyswietlHistorieWizyt(int idPac)
        {
            var Model = db.Wizyty.Where(w => w.PacjentID == idPac).ToList();
            return PartialView("ListaWizyt", Model);
        }

        public PartialViewResult pokazHistorie(int idwizy)
        {
            Wizyta wizyta = db.Wizyty.Find(idwizy);
            return PartialView("_KartaWizytyHistoria", wizyta);
        }


        public ActionResult DrukujWywiad(int idPac, string wyw)
        {
            Pacjent pac = db.Pacjenci.Find(idPac);
            WydrukWywiaduViewModel vm = new WydrukWywiaduViewModel
            {
                Pacjent = pac,
                Wywiad = wyw
            };
            return PartialView("Wydruk-Wywiad", vm);
        }

        public ActionResult DrukujRecepte(string[] leki, int lekarz, int pacjent)
        {
            Pacjent pac = db.Pacjenci.Find(pacjent);
            Pracownik prac = db.Pracownicy.Find(lekarz);
            WydrukRecepty wk = new WydrukRecepty { Pracownik = prac, Pacjent = pac, Leki = leki };

            return PartialView("_WydrukRecepta", wk);
        }



        public ActionResult ZapiszDodajWizyte([Bind(Include = "Id, Zalecenia,Skierowanie ,DataWizyty,DataModyfikacji,PacjentID,Pacjent,PracownikID,Pracownik,RezerwacjaId,Rozpoznanie,Wywiad,Badanie,Leki")] Wizyta wizyta, string submit)
        {
            if (submit == "wywiad")
            {
                return RedirectToAction("DrukujWywiad", wizyta);
            }
            else
            {
                db.Wizyty.Add(wizyta);
                var idrez = wizyta.RezerwacjaId;
                Rezerwacja rezerwacja = db.Rezerwacje.Find(idrez);
                rezerwacja.Stat = Status.Wykonany;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }



    }
}

SOPeL/Views/_Layout.cshtml
@{
    ViewBag.Title = "SOPeL";
    Layout = null;
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/reset")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/magnific")
    @Styles.Render("~/Content/Layout")
    @RenderSection("style", required: false)




    <meta name="description" content="System Obsługi Przychodni Lekarskiej" />
</head>
<body style="padding: 0" id="bodyPrzychodnia" class="maxSzerokosc maxWysokosc">
    <div class="maxWysokosc">
        <div class="sidebar hidden-xs" id="sidebarPrzychodnia">
            <div id="zwijaczMenu">
                <span class="glyphicon glyphicon-menu-left"></span>
                <span class="glyphicon glyphicon-menu-left"></span>
            </div>

            <ul id="navPortalPacjenta">
                <li id="Terminarz-Sidebar">
                    <a href="@Url.Action("Index","Terminarz")" id="Terminarz">
                        <img class="img-responsive" src="~/Content/Images/unnamed.png" alt="Terminarz" />
                        <span>Terminarz</span>
                    </a>
                </li>
                <li id="wizyta-sidebar">
                    <a href="@Url.Action("Index","Wizyta")" id="Wizyta">
                        <img class="img-responsive" src="~/Content/Images/heart-checkup.png" alt="Wizyta" />
                        <span>Wizyta</span>
                    </a>
                </li>
                <li id="admin-sidebar">
                    <a href="@Url.Action("Index","Admin")" id="Admin">
                        <img class="img-responsive" src="~/Content/Images/admin.svg" alt="Admin" />
                        <span>Admin</span>
                    </a>
                </li>
                <li id="pacjenci-sidebar">
                    <a href="@Url.Action("Index","Kartoteki")" id="Kartoteki">
                        <img class="img-responsive" src="~/Content/Images/KartotekiIcon.png" alt="Kartoteki" />
                        <span>Kartoteki</span>
                    </a>
                </li>
                <li id="pacjenci-sidebar">
                    <a href="@Url.Action("Index","Zestawienia")" id="Zestawienia">
                        <img class="img-responsive" src="~/Content/Images/ZestawieniaIcon.png" alt="Zestawienia" />
                        <span>Zestawienia</span>
                    </a>
                </li>
                <li id="home-sidebar">
                    <a href="@Url.Action("Index", "Przychodnia")" id="Home">
                        <img class="img-responsive" src="~/Content/Images/HomeIcon.png" alt="główna" />
                        <span>Ekran główny</span>
                    </a>
                </li>
            </ul>
            <div id="przychodnia-sidebar-footer">
                zalogowany
                @Html.ActionLink("Wyloguj", "Wyloguj", "Account")
            </div>


        </div>
        <div id="PrzychodniaBodyKontener" class="maxWysokosc">
            <div id="renderBody">

                @RenderBody()

            </div>
            <div class="wysrodkujCentralnie maxWysokosc maxSzerokosc ukryty" id="loader-kontener">
                <img id="loader" src="~/Content/Images/loader.gif" alt="Wczytuję..." />
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/magnific")
    @Scripts.Render("~/Scripts/Przychodnia")
    @RenderSection("scripts", required: false)

</body>
</html>